### ISSUE TITLE
I need a way to pass a "context" to a request so I can receive it in an Ok or Error

### ISSUE THREAD

**Issue by mhamrah** [sstone/amqp-client#16]
I would like to pass additional data with the Publish message so I can act on it when my sending actor receives an Ok or Error message.  Conceptually this data is just an object that is not part of the publish message but is important to manage the asynchronous coordination of actors.

I've come up with a nasty way of doing this (https://github.com/mhamrah/amqp-client/commit/0a145b804851f50abdab28347e3240ad7783a5e2) but I believe there to be a more elegant solution which should be part of the request trait.  I believe this context field should be optional and typed appropriately, but can't figure out how to make it unobtrusive with type parameters.

Any suggestions?

To apply a specific use case, I'm using amqp-client with the [Spray](spray/spray) library.  I want to pass along the current Spray RequestContext with the publish message, so my sending actor can call complete() or error() on the request object when receiving an Ok or Error message from the amqp-client.

**Comment by mhamrah** [comment]
As an alternative I was able to solve this with the current library by using the Ask pattern:

``` scala
 val result = producer ? Publish("dam.exchange", "asset.create", "yo!!".getBytes, properties=None, mandatory = true, immediate=false)
        result onComplete  {
          case Success(result) => {
            result match {
              case Amqp.Ok(request, response) => context.complete("success")
              case Amqp.Error(request, response) => context.complete("error")
            }
          }
          case Failure(failure) => println("x: " + failure)
        }
```

_context_ is the object which I would like to pass to Publish and receive back as a message to the Actor.  If though the Ask pattern works it is fairly verbose and I have to manage failure of the future and failure of the request.

**Comment by sstone** [comment]
I was about to ask why you didn't use the ask pattern with spray-routing :-) 
You might use mapTo/map/... to make it look less verbose ? something like:

``` scala
val future = (producer ? Publish("dam.exchange", "asset.create", "yo!!".getBytes, properties = None, mandatory = true, immediate = false))
.mapTo[Amqp.Ok]
.map(any => "success")
.recover { case _ => "error" }

ctx.complete(future)
```

**Comment by mhamrah** [comment]
Yes, I think that pattern will work well and appropriately leverages the compostability of futures.  Thanks for the help.
