### ISSUE TITLE
Alternate constructor for RabbitMQConnection

### ISSUE THREAD

**Issue by jkodumal** [sstone/amqp-client#21]
I'm planning on using the RabbitMQ Bigwig add-on for Heroku. Bigwig uses the `amqp` URI scheme for its configuration parameters, but there's no ctor for `RabbitMQConnection` that takes an AMQP URI. 

I worked around this by using the underlying Java client's `ConnectionFactory.setUri` method and then calling the `RabbitMQConnection` ctor with the values from the factory, but it'd be nice to avoid this.

**Comment by sstone** [comment]
It makes sense, I'll have a quick look at it. Thanks!

**Comment by sstone** [comment]
RabbitMQConnection has been removed, and ConnectionOwner takes a ConnectionFactory which can be created from a URI as described above.
