### ISSUE TITLE
Update to Akka 2.2.1

### ISSUE THREAD

**Issue by atif-frag** [sstone/amqp-client#23]
amqp-client needs update to 2.2.1

**Comment by magnusart** [comment]
Please, if possible could the project release a snapshot build that uses Akka 2.2.1? 
Just call it "1.2-AKKA2.2.1-SNAPSHOT" if you're not ready.

I had to do a publish local "1.2-LOCAL" build to continue, that works for my machine. But I would like for my colleagues to not have to do this. 

It seems as it was only to change the build.sbt akka version and it started working (for me).

**Comment by sstone** [comment]
Ok, I've just released version 1.2 for scala 2.10 (built against akka 2.1.4) which should be available on maven central shortly, updated 1.3-SNAPSHOT to use akka 2.2.1 and published a snapshot to the sonatype snapshot repo (https://oss.sonatype.org/content/repositories/snapshots/)

**Comment by magnusart** [comment]
Wonderful! Works fine from here.

**Comment by sstone** [comment]
Closing this issue but keeping #18 open for now.
