### ISSUE TITLE
When using the AMPQ client's Transaction the Header's Basic Properties are nulled out.

### ISSUE THREAD

**Issue by brycechesternewman** [sstone/amqp-client#25]
When using Transaction(List(Publish(...)) the code at https://github.com/sstone/amqp-client/blob/scala2.10/src/main/scala/com/github.sstone/amqp/ChannelOwner.scala#L139 calls new AMQP.BasicProperties.Builder().build(). I don't think this should occur and instead do something like val props = properties getOrElse new AMQP.BasicProperties.Builder().build().

**Comment by sstone** [comment]
Good catch, thanks!
