### ISSUE TITLE
Support for SSL - Passing ConnectionFactory as argument to RabbitMQConnection

### ISSUE THREAD

**Issue by soumikb** [sstone/amqp-client#31]
Currently, RabbitMQConnection doesn't seem to support SSL params (SSLContext) to the RabbitMQConnection.
It would be nice if the ConnectionFactory object was available for customized setting or if the RabbitMQConnection takes a SSLContext object as Optional param.

**Comment by sstone** [comment]
I'm thinking about dropping RabbitMQConnection, which is not that convenient after all. Can you please tell me if using ConnectionOwner directly works for you ?
Thanks

**Comment by soumikb** [comment]
Yes, using the ConnectionOwner also works for me.

**Comment by ashkan18** [comment]
Do you have a sample of SSL setup? Can't find any examples of usage of it? I looked at `ConnectionOwner` and can't find how we would handle `ampqs://`
