### ISSUE TITLE
Requests dropped during re-connect

### ISSUE THREAD

**Issue by ljcoomber** [sstone/amqp-client#34]
Hi,

When a ChannelOwner is disconnected, AMQP Requests are unhandled by the Actor, effective getting dropped. This can happen on high message throughput when a connection is dropped and re-connected.

I've put together a fix using a Stash in this commit: https://github.com/ljcoomber/amqp-client/commit/e801efb437326d1c56ad49b1f6f49279cd1e8531

If you're happy with the approach, I'll write some tests and submit a PR next week.

Cheers,

Lee

**Comment by sstone** [comment]
mmm.... If possible I'd like to know more about the use-case first. I don't mean to sound like a preachy old fart but though this type of requirements comes up very often in specs/early development stages in practice people soon find out that it might not be such a good idea (and it's not so easy to implement and to use). For example, I'm not aware of db drivers that would buffer request  in such a way
=> My gut feeling is that such buffering should be managed by the application and not the messaging driver: could you use status listeners and handle connection events on the app side instead ?
 Otherwise, maybe this buffering behaviour could be made optional and deactivated by default ?
Thanks

**Comment by ljcoomber** [comment]
That's a fair point.

The use cases are mixed but the common theme is that we rely on the broker
for at-least-once delivery. I agree that ideally applications deal with
message delivery guarantees (de-duping, re-tries etc), but it would be very
heavyweight for some of the use cases (bridging), and out of our hands for
others (talking to 3rd party products).

That said, the guarantees RabbitMQ provides are adequate for us so we have
started some testing to ensure everything works end-to-end.

I agree that the behaviour should be optional and should not break existing
users.

Re: DB drivers, I agree, but I haven't used any async ones. With
synchronous drivers the caller will know immediately that the connection
has been terminated. In an async scenario, I would expect the caller to be
notified of failure automatically. This may be my lack of experience with
Akka, and now that I am aware of the behaviour I know how to mitigate it by
adding status listeners at the app level, or perhaps overriding unhandled()
to catch when this problem arises and deal with it.

I'll need to think about it for a bit, but my initial feeling is that
tracking connection status at an app level is unnecessary duplication and
leaks some of the AMQP domain up higher than necessary. Overriding
unhandled() may be better but does have a similar problem, and I'd be
interested in your thoughts as an experienced Akka user as to how idiomatic
that would be.

A third option would be to add a failure case class wrapping a request,
which is returned to the sender if the connection is down.

Many thanks

**Comment by sstone** [comment]
I don't think it is specific to akka or rabbitmq: suppose you're a node in a distributed system that communicates with other nodes through async message passing, and you find out that you are cut from the other nodes, and you can't really know why. What happens next is app-dependent but very often messages than cannot be sent are just dropped, and some kind of registry/cluster membership system handles nodes coming up and down. You may also need to handle ack/nack and flow control issues. 
But I agree that is your are bridging 2 different systems (an http frontend maybe ?) what you propose might be a very good approach, and it's very simple too
=>  you could  test this with your app under"real conditions" (if possible), make this buffering behaviour optional, and if it works for you I'll merge the PR ?

returning a "failure" message to the sender that wraps the original request when the chanel actor is disconnected also sounds like a good idea.

Thanks!

**Comment by ljcoomber** [comment]
Hi, yes, there will always be cases where messages can be dropped, but in this case we can communicate failure immediately. 

Re: stashing, I think you are right that it needs to be handled at an app layer. Stashing breaks flow control and hides the problem from the app layer.

I've gone with the adding a "failure" message... PR coming up...
