### ISSUE TITLE
Removing/cancelling a consumer

### ISSUE THREAD

**Issue by soumikb** [sstone/amqp-client#35]
Hi, 
 This is more of a query (or feature request) in that I've a use case where I do want to stop consuming messages off a connection. I would think that equivalent to CreateConsumer, there should be a RemoveConsumer as well so that I can gracefully stop consuming messages off a particular queue. (The motivation behind this is for me to have a FSM or Actor become transition which on receipt of one message on a queue - q1, starts listening on another queue q2. And stops getting Delivery callbacks for q1.) 

RabbitMQ Java client does seem to expose basicCancel(java.lang.String consumerTag), which does the same. I was wondering if similarly a newly created CancelConsumer case class could be handled by ChannelOwner, to remove an existing consumer.

Any thoughts?

Thanks,
Soumik

**Comment by sstone** [comment]
Hi,
It makes sense. Right now it should be possible to achieve by stopping and creating Consumer actors (stop Consumer for q1, create a new Consumer actor for q2). Can please tell me if it works ? (may be I missed something). But I agree it should be simpler, I'll try and think of something.
Thanks!

**Comment by mgrenonville** [comment]
Hello, 

At Mediarithmics, we needed this functionnality, so we code it. The pull request will follow.

Basically, there is a new case class CancelQueue(queueName: String). It will cancel all listeners binded to queueName, since the library is not exposing the consumerTag.

Thank you for your great library !

**Comment by sstone** [comment]
Hi,
I've been thinking about this and will update the Consumer class asap. Would creating a new Consumer actor with the new binding and stopping the old one work in your case ?
Thanks!

**Comment by mgrenonville** [comment]
Hi, 

Thank you for your feedback ! Basically, I've not tested to kill/recreate the actor, because I needed to be able to unbind the consumer but continue to Acknowledge pending messages. I've updated the tests in the pull request to show you my case.

Have a great day.

**Comment by sstone** [comment]
Ok, I think I understand what you need. I'll try and update this asap.
Thanks!

**Comment by sstone** [comment]
Hi,
I've just added a new CancelConsumer request and an example that demonstrates how to switch between queues (see https://github.com/sstone/amqp-client/blob/scala2.10/src/main/scala/com/github.sstone/amqp/samples/Consumer4.scala). 
Can you please tell me if it matches your use case ?
Thanks
ps. I've already pushed a snapshot to the sonatype snapshot repo

**Comment by soumikb** [comment]
Thanks a lot!
Thats exactly what I needed.

**Comment by sstone** [comment]
You're welcome!
