### ISSUE TITLE
Support for Akka 2.2.3

### ISSUE THREAD

**Issue by durgadeep** [sstone/amqp-client#37]
Hi folks,

  The latest stable version of Akka (http://akka.io/docs/)
   Akka 2.2.3 (current stable release) for Scala 2.10

   But from the sstone

   https://github.com/sstone/amqp-client
  amqp-client 1.3 is compatible with Scala 2.10 and Akka 2.2

Is there a plan / interim for us to use Sstone with Akka 2.2.3 

Thanks a bunch

**Comment by sstone** [comment]
Hi,
2.2 means 2.2.X (minor versions are supposed to be binary compatible) so you can use 1.3-ML4 with akka 2.2.3
