### ISSUE TITLE
1.3-ML4 Queries 

### ISSUE THREAD

**Issue by rohitgupta-90** [sstone/amqp-client#39]
We need to upgrade to latest Akka release in our application, and thereby also upgrade the amqp-client library accordingly. 
I see that there is a milestone release of the amqp-client 1.3-ML4 that is compatible with latest Akka release.
1) Is there any plan of having another release in the near future? 
2) Can/Should the 1.3-ML4 milestone be used in the production?

Thanks,
Rohit

**Comment by sstone** [comment]
Hi Rohit,
1) Yes, I will release 1.3 soon (in about a week)
2) 1.3-ML4 is being used in production already (but  of course it does not mean that it is bug-free) so I would answer yes too. It also means that I will try and fix new issues as quickly as possible 
Thanks
