### ISSUE TITLE
Update to akka 2.3.0

### ISSUE THREAD

**Issue by akhil** [sstone/amqp-client#41]
akka needs update to 2.3.0

**Comment by sstone** [comment]
Version 1.4 will target akka 2.3.0, the first snapshots should be available by the end of next week. 
For now, you can just edit the pom, recompile and generate your own snapshot.
Thanks

**Comment by peter-svensson** [comment]
Hi,
Any plans on doing a release for the 1.4 track? I've built locally with Akka v2.3 and all my code seems to be working just fine. I did build on the 1.3-ML5 tag and not the 1.4-ML4 though since we've used 1.3-ML5 before.

**Comment by sstone** [comment]
version 1.4 uses Akka 2.3.2 and has been released for scala 2.10 and scala 2.11. It should be available on maven central in a few hours.
Thanks

**Comment by peter-svensson** [comment]
Great news! However it seems that its still unavailable in any Maven repo I can find...

**Comment by sstone** [comment]
Sorry about that, I had not fully completed the release process. It is now available on maven central.
Thanks
