### ISSUE TITLE
Consumer Cancellation Notifications

### ISSUE THREAD

**Issue by vishramachandran** [sstone/amqp-client#43]
SStone AMQP Library needs to recognize and handle Consumer Cancellation Notifications as mentioned in 

http://www.rabbitmq.com/ha.html
http://www.rabbitmq.com/consumer-cancel.html

Without this, it is hard to use this library in clustered production scenarios. 

Quoting from ha.html:

Clients that were consuming from the mirrored-queue and support our Consumer Cancellation Notifications extension will receive a notification that their subscription to the mirrored-queue has been abruptly cancelled. At this point they should re-consume from the queue, which will pick up the new master. The reason for sending this notification is that informing clients of the loss of the master is essential: otherwise the client may continue to issue acknowledgements for messages they were sent by the old, failed master, and not expect that they might be about to see the same messages again, this time sent by the new master. Of course, clients that were connected to the failed node will find their connections failed, and will need to reconnect to a surviving node of the cluster.

Spring AMQP had a similar bug that was fixed:
https://jira.spring.io/browse/AMQP-209

**Comment by sstone** [comment]
I've added support for consumer cancellations and published a snapshot to the sonatype snapshot repo. I have not tested it yet with a clustered broker but I've simulated a broker-generated customer cancellation by deleted a queue with the admin tools and checking that it works with the following test: https://gist.github.com/sstone/9951220
Can you please tell me if it works for you ?
Thanks

**Comment by vishramachandran** [comment]
Thanks for the quick turnaround. If the queue is recreated after deletion, will the consumer reconnect to the new queue and continue to receive the messages?

**Comment by sstone** [comment]
Not automatically, you will have to react to a ConsumerCancelled message send an AddQueue or AddBinding message to the consumer.

**Comment by vishramachandran** [comment]
Since this is more like a "reconnect" it would be great if the library can abstract out the re-consumption from the queue if it can be done in a certain number of attempts.  Spring AMQP does have this behavior.

**Comment by sstone** [comment]
I have not yet found a satisfying solution to automatically reconnect consumers (and honestly I'm not yet convinced it would be practical). It seems (from you question on the RabbitMQ ML) that now the broker takes care of this. Is it good enough for you, or would you also like to have a solution for previous versions of the broker ?
thanks

**Comment by vishramachandran** [comment]
This should be fine. If for whatever reason RMQ 3.3 does not work out for us, we'll switch to the fix you have provided, and reconsume ourselves.

Thanks for your follow up.
