### ISSUE TITLE
Custom ExecutionContext for RpcServer

### ISSUE THREAD

**Issue by slorion** [sstone/amqp-client#45]
Hello,

I would like to use a custom ExecutionContext (delegating the execution to the global one after having done some preparations). If I understand your code correctly, it is not possible to do that currently because ExecutionContext.Implicits.global is used directly, but an additional constructor argument would allow that.

Please let me know if I guessed correctly and if so, I will create a pull request that will add the argument with ExecutionContext.Implicits.global as default value.

As a side note, what would be the best way to store data that is to be saved/restored with the ExecutionContext (e.g. a shared transaction context) ? I try to find how to do that, but to no avail.

Thank you!

**Comment by sstone** [comment]
Hi,
You're right about the execution contexts. It should be enough to add (implicit ctx: ExecutionContext = ExecutionContext.Implicits.global) is it what you had in mind ?
I'm sorry but I'm not sure that I really understand you question about state and execution contexts.
Thanks!

**Comment by slorion** [comment]
Yes, that's exactly what I had in mind. The change does ripple a bit to
Props,  but that's all.

As for my other question, if I am more specific, what I am trying to do is
associate a transaction context to an actor when it is running a transacted
operation. That external state should be saved/restored on whichever thread
is running the actor. Other than simply keeping a reference to that state
in the actor itself, is there some more generic way to associate an
external state with an actor? I would prefer that as it would make the
design less coupled.

Thank you again!

**Comment by slorion** [comment]
I saw that a ThreadLocal could be used in conjunction with a CapturingExecutionContext as done by Viktor Klang here: https://gist.github.com/viktorklang/8652944. It am not sure it is an ideal solution, but it would work.

**Comment by slorion** [comment]
I created a PR: https://github.com/sstone/amqp-client/pull/46. I cannot find a way to link this issue with the PR thought.
