### ISSUE TITLE
Update to RabbitMQ Java Client 3.3.0

### ISSUE THREAD

**Issue by soumikb** [sstone/amqp-client#47]
More of a request for enhancement than an issue - but, is there a plan to move the milestone release to the latest RabbitMQ Java client - 3.3.0?
It seems a bunch of security fixes have gone in the for RabbitMQ from 3.2.1 to 3.3.0 - it would be nice if the amqp-client is updated with the java client aswell to take advantages of those fixes.

**Comment by soumikb** [comment]
Updated to the latest 1.3. Thanks.

**Comment by Keruspe** [comment]
It would be great to get a release out with this

**Comment by sstone** [comment]
Hi,
Version 1.4 (which is available on maven central for scala 2.10 and 2.11) uses version 3.3.1 of the rabbitmq java client.
Thanks

**Comment by Keruspe** [comment]
version 1.4 for scala 2.10 seems to be using version 3.2.1 here. scala 2.11 is ok.

**Comment by sstone** [comment]
Version 1.4 on maven central does seem to use version 3.3.1 of rabbitmq client: http://search.maven.org/#artifactdetails|com.github.sstone|amqp-client_2.10|1.4|jar

Can you check in your local repo the pom that was downloaded along with the client jar ? if should be the same as the one on maven central.

Thanks
