### ISSUE TITLE
Actor doesn't get Garbage Collected

### ISSUE THREAD

**Issue by ahaid** [sstone/amqp-client#55]
I've got a publisher and multiple consumer objects (singletons) that create the actor system and instantiate the actor per your examples. However, I'm finding that as messages go through the system, there is no garbage collection done on the actor. Therefore memory eventually fills up and it comes to a screeching halt. What can I do to enable GC of vals that are out of scope? I want everything inside the `receive` function to be GC'd.

Here is my publisher:

```
object Publisher  {
  implicit val system = ActorSystem(LibContext.akkaConfig.system)
  val connFactory = new ConnectionFactory()
  connFactory.setUri(LibContext.rabbitConfig.uri)
  val conn = system.actorOf(ConnectionOwner.props(connFactory, 5 second))

  private val channel = ConnectionOwner.createChildActor(conn, ChannelOwner.props())
 Amqp.waitForConnection(system, channel).await()

 class Producer extends Actor {
val logger = LoggerFactory.getLogger(this.getClass)
logger.info("Starting publisher")

channel ! ConfirmSelect
channel ! AddReturnListener(self)
channel ! AddConfirmListener(self)
def receive = {
  case message: QueueableMessage => {
    logger.info("publishing message from exchange:" + message.exchangeType)
    val props = new AMQP.BasicProperties("application/json", "utf-8", null, 2, 1, "", "", null, message.messageType, new DateTime(message.createdOn).toDate, message.messageType, LibContext.rabbitConfig.user, "", "")

    val mapper = new ObjectMapper
    mapper.registerModule(DefaultScalaModule)

    // Declare the exchange if it's specified in the message
    if (message.exchangeType != None) {
      channel ! DeclareExchange(ExchangeParameters(message.exchangeType.get.toString, false, QueueUtils.getExchangeType(message.exchangeType.get), durable = true))
      channel ! Publish(message.exchangeType.get.toString, message.messageType, mapper.writeValueAsBytes(message), Option(props))
    }
    else {
      channel ! DeclareQueue(QueueParameters(name = message.messageType, passive = false, durable = true, exclusive = false, autodelete = false))
      channel ! Publish("", message.messageType, mapper.writeValueAsBytes(message), Option(props))
    }
    channel ! WaitForConfirms(None)
  }

  }
}
val producer = system.actorOf(Props[Producer], "Producer")

def publishMessage(message: QueueableMessage){
  producer ! message
}
}
```

**Comment by sstone** [comment]
Hi,
Sorry but I'm not sure that I fully understand what you mean  by "actor doesn't get GCed". Have you tried profiling (with jvisualvm or jprofile) to identify what is eating up memory ? Is it how you came to the conclusion that there is a pb with the receive call ?
Also, Is it possible to reproduce with issue with a simple and complete code sample ? I cannot run your sample, but I don't see anything wrong with (though I wonder why "val mapper = new ObjectMapper" is inside receive)
Thanks!

**Comment by ahaid** [comment]
It seems my problem stems from an issue with the Actor system. See this SO issue: http://stackoverflow.com/questions/23066264/can-wrapping-akka-actors-in-a-class-cause-memory-leaks

> "There is no automatic garbage collection for actors since they are distributed entities by nature and the JVM does not support distributed GC." 

My Publisher starts up when the app starts and a steady stream of messages flow through it. It doesn't get shut down until the app does and that isn't supposed to happen unless I push a new release. Every message that goes through the Publisher has a small conversion happen to it to create a byte array. The byte arrays end up completely taking over the heap. They are never GC'd. I profiled it with jvisualvm.

My question is: Using a similar pattern to your samples (as mine is), have you ever needed to shut down the actor then start it back up again to free up memory?

**Comment by ahaid** [comment]
I seem to have solved my own problem. I moved the instanciation of the Producer actor into the publishMessage function then immediately send it a PoisonPill. This has stopped the uncontrollable heap growth and GC is cleaning up nicely. 

```
def publishMessage(message: QueueableMessage){
  val producer = system.actorOf(Props[Producer], "Producer")
  producer ! message
  producer ! PoisonPill
}
```

**Comment by sstone** [comment]
Ok, glad to know you've worked it out. 

Out of curiosity, is the conversion that creates the byte arrays the fill up memory performed by ObjectMapper ? If so is it possible to either:
- comment out the code that create the mapper and use a fixed value (such as "test".toBytes instead) 
- or move the "new ObjectMapper()" out of receive() 
  and see if the issue is still there ? 

Thanks

**Comment by ahaid** [comment]
Oops, prematurely closed this issue. The problem wasn't solved then but it is now. 

The problem wasn't the ObjectMapper although I did move it out of the `receive` function while troubleshooting the memory leak. In the end I had to dump the actors and use the rabbitmq java library to publish. I still have the actor based consumers working with no memory leaks but the publisher couldn't handle it.

Have you tested this library with a large, steady stream of messages? I couldn't get it to work.

Here's my Publisher now:

```
object Publisher {

  // create an AMQP connection
  val connFactory = new ConnectionFactory()
  connFactory.setUri(LibContext.rabbitConfig.uri)
  val conn = connFactory.newConnection()
  val channel = conn.createChannel

  def publishMessage(message: QueueableMessage) = {
    val props = new AMQP.BasicProperties("application/json", "utf-8", null, 2, 1, "", "", null, message.messageType, new DateTime(message.createdOn).toDate, message.messageType, LibContext.rabbitConfig.user, "", "")

    // Declare the exchange if it's specified in the message
    if (message.exchangeType != None) {
      channel.exchangeDeclare(message.exchangeType.get.toString, QueueUtils.getExchangeType(message.exchangeType.get), true)
      channel.basicPublish(message.exchangeType.get.toString, message.messageType, props, message.messageBytes)
    }
    else {
      channel.exchangeDeclare(message.messageType, "direct", true)
      channel.queueDeclare(message.messageType,true,false,false,null)
      channel.queueBind(message.messageType, message.messageType, message.messageType);
      channel.basicPublish(message.messageType, message.messageType, props, message.messageBytes)
    }
  }
}
```

And in an attempt to head off any confusion, here's my QueueableMessage trait. 

```
trait QueueableMessage extends Deserializer {
  val messageType: String = getClass.getSimpleName
  val exchangeType: Option[SolidFireExchange] = None
  val createdOn: String = DateTime.now(DateTimeZone.UTC).toDateTimeISO.toString
  val messageBytes = mapper.writeValueAsBytes(this)
}
```

Note that `Deserializer` has an ObjectMapper in it so you can see I pushed it as far away from the Publisher as I could.

**Comment by sstone** [comment]
There are long-running server apps using this library with steady message streams and afaik they are quit stable (which of course does not mean there is no issue).
The producer in this gist https://gist.github.com/sstone/b1a95a7fe8ed65483ed1 seems to be ok memory-wise, can you use it as a starting point and try and reproduce the pb ? 
Thanks!

**Comment by ahaid** [comment]
Interestingly, that works. I don't know why. Here's my producer now and it gets GC'd perfectly fine. Thank you for your help and prompt replies.

```
  object Publisher {
    implicit val system = ActorSystem(LibContext.akkaConfig.system)

    val connFactory = new ConnectionFactory()
    val servers =  for (server <- LibContext.rabbitConfig.hosts.split(",")) yield new Address(server, LibContext.rabbitConfig.port)

    // create an AMQP connection
    connFactory.setUsername(LibContext.rabbitConfig.user)
    connFactory.setPassword(LibContext.rabbitConfig.password)

    val conn = system.actorOf(ConnectionOwner.props(connFactory, 5 second, None, Option(servers)))

    val channel = ConnectionOwner.createChildActor(conn, ChannelOwner.props())
    Amqp.waitForConnection(system, channel).await()

    class Producer extends Actor with ActorLogging {
      channel ! ConfirmSelect
      channel ! AddReturnListener(self)
      channel ! AddConfirmListener(self)

      override def unhandled(message: Any): Unit = message match {
        case Amqp.Ok(_, _) => ()
        case _ => log.warning(s"unhandled $message")
      }
      def receive = {
        case message: QueueableMessage => {
          val props = new AMQP.BasicProperties("application/json", "utf-8", null, 2, 1, "", "", null, message.messageType, new DateTime(message.createdOn).toDate, message.messageType, LibContext.rabbitConfig.user, "", "")

          // Declare the exchange if it's specified in the message
          if (message.exchangeType != None) {
            channel ! DeclareExchange(ExchangeParameters(message.exchangeType.get.toString, false, QueueUtils.getExchangeType(message.exchangeType.get), durable = true))
            channel ! Publish(message.exchangeType.get.toString, message.messageType, message.messageBytes, Option(props))
          }
          else {
            channel ! DeclareQueue(QueueParameters(name = message.messageType, passive = false, durable = true, exclusive = false, autodelete = false))
            channel ! Publish("", message.messageType, message.messageBytes, Option(props))
          }
          channel ! WaitForConfirms(None)
        }
        case Amqp.Ok(WaitForConfirms(_), _) => self ! "confirm"
        case HandleAck(_, _) => ()
      }
    }

    val producer = system.actorOf(Props[Producer], "Producer")


    def publishMessage(message: QueueableMessage) = {
      producer ! message
    }
  }
```

**Comment by sstone** [comment]
I've thought of another situation that could lead to OOM errors: an overflow of messages sent to the producer that exceeds its publishing capabilites: the channel actor queue fills up and you run out of memory. This is why in the gist above I wait for the reply to WaitForConfirms() before the next message is sent.
Thanks!
