### ISSUE TITLE
wrong sha1 for amqp-client_2.11-1.5.pom on maven central repo

### ISSUE THREAD

**Issue by rcristian** [sstone/amqp-client#63]
Here's a snippet from a sbt project that has this package as a dep:

`[info] Resolving com.github.sstone#amqp-client_2.11;1.5 ...
[warn] problem while downloading module descriptor: https://repo1.maven.org/maven2/com/github/sstone/amqp-client_2.11/1.5/amqp-client_2.11-1.5.pom: invalid sha1: expected=42e068568008f5994a4d5ef3f425470be7c0fe35 computed=5b68b5b75889e94c2c7892fcecfa7f5010d27dcc (460ms)`

**Comment by sstone** [comment]
It seems that the checksum on maven central is bad indeed, I'll try and check what might have gone wrong in the staging phase. I'll update this issue asap.
Meanwhile you can just clone and compile amqp-client (yes I got this tip from Captain Obvious :))
Thanks!

**Comment by sstone** [comment]
Ok, checksums should be correct now.
Thanks!
