### ISSUE TITLE
Getting future timeout exception which creating a consumer/producer

### ISSUE THREAD

**Issue by anindyaju99** [sstone/amqp-client#69]
I am consistently getting the following timeout exception with ~100 producer and equal number consumers (same VM, different queues on a rmq cluster, same connection ActorRef). Is this a bug or this is expected? If yes, how can I increase the timeout?

@400000005640a96d37c7c70c 2015-11-09 19:40:43,935 - [ERROR] -  akka.actor.OneForOneStrategy - Futures timed out after [5000 milliseconds]
@400000005640a96d37c7caf4 akka.actor.ActorInitializationException: exception during creation
@400000005640a96d37c7cedc at akka.actor.ActorInitializationException$.apply(Actor.scala:164) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c7cedc at akka.actor.ActorCell.create(ActorCell.scala:596) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c7d2c4 at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:456) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c82c9c at akka.actor.ActorCell.systemInvoke(ActorCell.scala:478) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c83084 at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:263) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c8346c at akka.dispatch.Mailbox.run(Mailbox.scala:219) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c83854 at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c84bdc at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c84fc4 at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c86734 at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c86b1c at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c86f04 Caused by: java.util.concurrent.TimeoutException: Futures timed out after [5000 milliseconds]
@400000005640a96d37c87ea4 at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:219) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c8828c at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c88674 at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:190) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c89614 at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c899fc at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640) [dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c8ad84 at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c8b16c at scala.concurrent.Await$.result(package.scala:190) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c8b554 at com.github.sstone.amqp.ConnectionOwner$.createChildActor(ConnectionOwner.scala:32) ~[dispatcher-service.jar:1.8-SNAPSHOT]
@400000005640a96d37c8c10c at com.olacabs.dispatcher.rmq.RabbitMQConnectionHelper$.createProducer(RabbitMQConnectionHelper.

**Comment by sstone** [comment]
It seems that RabbitMQConnectionHelper you are calling ConnectionOwner.createChildActor() and it times out. This method has a timeout parameter which defaults to 5 seconds. You could try with a higher value and see if you get the same error ?

Did you check the rabbitmq logs ? Was there anything suspicious there ?

However this is really unexpected and no such problems have been reported yet. Do you have a small and self-contained sample that I could use to investigate ?

Thanks

**Comment by anindyaju99** [comment]
This was because of heavy load on the RMQ cluster. Most likely (though very difficult to pin point), the consumer actors were receiving the messages from RMQ but were dropping them! So the application was not getting the messages. We found some evidence in support of this theory - our actors we not getting messages but RMQ was showing delivered (not acked) messages. But as I said, it's very difficult to pin point this. Also, we have some other language drivers for RMQ and they were working fine (in other applications) with this same RMQ cluster. I don't know how you can reproduce/fix this. But it would be nice if in such cases an error is thrown instead of silently dropping messages.
