### ISSUE TITLE
Update build.sbt to rabbitmq version 3.6.1

### ISSUE THREAD

**Issue by brycechesternewman** [sstone/amqp-client#77]
Hi,
I noticed the scala2.11 branch the pom.xml uses the latest version of rabbitmq. Can we also update the build.sbt or are there some reservations about doing so?
Thank you.
Bryce

**Comment by sstone** [comment]
Hi,
Sorry for not replying earlier. I don't really mind, but I will remove the sbt build soon (before I release 1.6) so it won't be there for long. It's a simple build so I guess that people will be able to easily create their own if they need to.
Thanks!

**Comment by brycechesternewman** [comment]
👍  Thank you for letting me know built.sbt will eventually be removed
