### ISSUE TITLE
How to cleanly close a channel owner?

### ISSUE THREAD

**Issue by anindyaju99** [sstone/amqp-client#81]
My application needs ephemeral queues. I delete queues once done -

consumerRef ! DeleteQueue(inputQConfig.queue)

This is having two problems -
- < 10% of times this is not deleting the queue.
- The consumer (channel owner) actor is not killed. Hence the channel is open.
  I don't reuse the consumer actor for other queues.

What is the clean way of ensuring the consumer and channel is closed properly?

**Comment by sstone** [comment]
Hi,
The clean way to close the channel would be to just stop the actor that owns it. Once the queue has no more consumers the broker will automatically delete it (I assume that by ephemeral you mean auto-delete). I've modified one of the sample to illustrate this: https://gist.github.com/sstone/1066b4ab3c875b84c1ab6b803d6d47e4.
The first time you press enter, the consumer actor is stopped and the queue is deleted (you can check this with the management plugin if you've enabled it).

Thanks!

**Comment by anindyaju99** [comment]
Thanks.

For my use case ephemeral does not mean auto-delete. I have multiple consumer/producers for a queue. When they are done (detected by code residing outside the actors), the application actors get a PoisonPill on which they kill the actors (with a DeleteQueue message to the channel owner).

May be not the right forum to ask, but what is the difference between actorSystem.stop(actorRef) and "actorRef ! PoisonPill". I couldn't find any discussion on that.

Also, is it safe to rewrite your example to do -

consumerRef ! DeleteQueue(.....)
system.stop(consumerRef) // or consumerRef ! PoisonPill

Is there a race condition where the consumer would be stopped before the DeleteQueue message is completely processed?

**Comment by sstone** [comment]
My understanding is that system.stop(actor) will stop the actor as soon as it is done processing its "current" message, while with actor ! PoisonPill  the actor will process all received messages up to PoisonPill. Which means that you're right: it is indeed possible that stop() will stop the actor before it has processed the DeleteQueue message.
