### ISSUE TITLE
How to create more than one channels?

### ISSUE THREAD

**Issue by Yi-G** [sstone/amqp-client#82]
Hi,
can I call more than one times 
`val consumer = ConnectionOwner.createChildActor(conn, Consumer.props(listener, channelParams = None, autoack = false))
`
method to create more channels. 

In my use case, I need more channels, but the same channel listener.

thanks in advance!
Yi

**Comment by sstone** [comment]
Hi,
Yes, you can create as many channels as you want.
Thanks!

**Comment by Yi-G** [comment]
Thanks :) I'll close the issue.
